"""empty message

Revision ID: 250b845bf6e9
Revises: da8e5df7ef74
Create Date: 2017-11-07 22:02:10.696968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250b845bf6e9'
down_revision = 'da8e5df7ef74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_items', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('stock_items', sa.Column('stock_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_items', 'stock_count')
    op.drop_column('stock_items', 'note')
    # ### end Alembic commands ###
