"""empty message

Revision ID: 3182b0f012f1
Revises: 84898f9a2713
Create Date: 2018-03-31 21:26:08.890103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3182b0f012f1'
down_revision = '84898f9a2713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchaseitem', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('purchaseitem', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchaseitem', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchaseitem', type_='foreignkey')
    op.drop_column('purchaseitem', 'user_id')
    op.drop_column('purchaseitem', 'note')
    # ### end Alembic commands ###
