"""empty message

Revision ID: 6458082b93e4
Revises: d61754fa27a1
Create Date: 2017-11-09 13:36:53.919963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6458082b93e4'
down_revision = 'd61754fa27a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('track', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'track')
    # ### end Alembic commands ###
