"""empty message

Revision ID: 768fe0d1a2a6
Revises: 7df682ea7645
Create Date: 2017-11-11 20:59:31.502807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768fe0d1a2a6'
down_revision = '7df682ea7645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchaseitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('get_price', sa.Float(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchaseitem')
    # ### end Alembic commands ###
