"""empty message

Revision ID: 7b2ae99b6a2b
Revises: 9901beb65045
Create Date: 2017-11-09 12:27:45.107879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2ae99b6a2b'
down_revision = '9901beb65045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('stock_items', sa.Column('order_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_items', 'order_count')
    op.drop_column('order_items', 'status')
    # ### end Alembic commands ###
