"""empty message

Revision ID: 7df682ea7645
Revises: 6458082b93e4
Create Date: 2017-11-09 13:52:15.901833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df682ea7645'
down_revision = '6458082b93e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('shipped_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'shipped_count')
    # ### end Alembic commands ###
