"""empty message

Revision ID: 84898f9a2713
Revises: bd74e06be2de
Create Date: 2018-03-23 21:47:18.234398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84898f9a2713'
down_revision = 'bd74e06be2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_items', 'shipped_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_items', sa.Column('shipped_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
