"""empty message

Revision ID: 9901beb65045
Revises: 250b845bf6e9
Create Date: 2017-11-07 22:19:27.304478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9901beb65045'
down_revision = '250b845bf6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('stock_count', sa.Integer(), nullable=True))
    op.drop_column('stock_items', 'stock_count')
    op.drop_column('stock_items', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_items', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('stock_items', sa.Column('stock_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('order_items', 'stock_count')
    op.drop_column('order_items', 'note')
    # ### end Alembic commands ###
