"""empty message

Revision ID: bd74e06be2de
Revises: e9d157f2b3ee
Create Date: 2018-03-23 13:58:05.592082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd74e06be2de'
down_revision = 'e9d157f2b3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('released', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'released')
    # ### end Alembic commands ###
