"""empty message

Revision ID: d61754fa27a1
Revises: 7b2ae99b6a2b
Create Date: 2017-11-09 13:33:53.889264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61754fa27a1'
down_revision = '7b2ae99b6a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('orderitem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orderitem_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    # ### end Alembic commands ###
